### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by anotheri** [circuithub/mail-listener#11]
When I try to start mailListener from your example for `host: "imap.gmail.com",  port: 993` I have next error (node v0.10.4):

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Hostname/IP doesn't match certificate's altnames
    at SecurePair.<anonymous> (tls.js:1292:23)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:896:10)
    at CleartextStream.read [as _read] (tls.js:430:15)
    at CleartextStream.Readable.read (_stream_readable.js:294:10)
    at EncryptedStream.write [as _write] (tls.js:344:25)
    at doWrite (_stream_writable.js:211:10)
    at writeOrBuffer (_stream_writable.js:201:5)
    at EncryptedStream.Writable.write (_stream_writable.js:172:11)
    at write (_stream_readable.js:547:24)
```

**Comment by chirag04** [comment]
This issue is not related to mail-listener but node-imap library which is a dependency of mail-listener.

Node-imap library is having some issues with node version after 8.23 i guess. Try using node v8.23

If you still want to use node v10, You need to manually apply the below patch to node-imap library:

https://github.com/mscdex/node-imap/issues/181#issuecomment-15882892

**Comment by anotheri** [comment]
@chirag04 thank you very much!

**Comment by alexiskattan** [comment]
+1
