### ISSUE TITLE
Error: read ECONNRESET. And how can it works by day and night (24/7)?

### ISSUE THREAD

**Issue by anotheri** [circuithub/mail-listener#14]
Sometimes I have that error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:883:11)
    at TCP.onread (net.js:539:19)
```

I think it occur when my internet connection is down. But when I try to catch it by force disconnect my internet connection `mail-listener` continues to work correctly and even read incomming emails. But sometimes it throw error.

**Comment by anotheri** [comment]
For testing `mail-listener` behaviour without internet connection I do next listeners:

```
mailListener.on("server:connected", function(){
  console.log("imapConnected");
  setTimeout(function() {
    mailListener.stop();
  }, 10000);
});

mailListener.on("server:disconnected", function(){
  console.log("imapDisconnected");
  setTimeout(function() {
    mailListener.start();
  }, 20000);
});
```

So if I disconnect after `imapDisconnected` message I've got next error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

And if I disconnect internet after `imapConnected` message it stay runned but doesn't send any logs.

Maybe do you have any ideas how I can handle this cases?

**Comment by podviaznikov** [comment]
Hi, thanks for posting this issue.

Somehow I wasn't able to reproduce this problem with your coe.

My output looks fine.

```
imapConnected
19 Apr 18:53:24 - open mail box 'INBOX': success
19 Apr 18:53:24 - found 0 emails
19 Apr 18:53:24 - no email were found
imapDisconnected
19 Apr 18:53:55 - connect to mail server: success
imapConnected
19 Apr 18:53:56 - open mail box 'INBOX': success
19 Apr 18:53:56 - found 0 emails
19 Apr 18:53:56 - no email were found
imapDisconnected
19 Apr 18:54:27 - connect to mail server: success
imapConnected
19 Apr 18:54:27 - open mail box 'INBOX': success
19 Apr 18:54:27 - found 0 emails
19 Apr 18:54:27 - no email were found
imapDisconnected
```

What version of node, imap and mail-parser are you using?

**Comment by anotheri** [comment]
@podviaznikov I have patched imap for node v0.10.4.

```
$ npm list
/home/alexander/www/new
└─┬ mail-listener@0.6.2
  ├─┬ imap@0.7.8
  │ └── utf7@1.0.0
  └─┬ mailparser@0.3.4
    ├─┬ encoding@0.1.6
    │ └── iconv-lite@0.2.7
    ├── iconv@2.0.4
    ├── mime@1.2.9
    └─┬ mimelib@0.2.12
      └── addressparser@0.1.3

$ node -v
v0.10.4

```

**Comment by chirag04** [comment]
@podviaznikov What was the patch? Did you send a PR?

**Comment by alexiskattan** [comment]
was this pushed to npm?

**Comment by anotheri** [comment]
@chirag04 
@alexiskattan 
It was just [Allow custom TLS options (fix #181)](https://github.com/mscdex/node-imap/commit/0b042e0e14dfde6a26e881bbbcf0c6f9746da51e) for imap from [this thread](https://github.com/mscdex/node-imap/issues/181#issuecomment-15882892), nothing new.

**Comment by anotheri** [comment]
@podviaznikov 

> Somehow I wasn't able to reproduce this problem with your coe.
> My output looks fine.

Yes, it should looks fine if you have stable internet connection.
Try to interrupt internet connection (turn off ethernet or wi-fi) at the next moments:
— when you see `imapDisconnected`,
— when you see `imapConnected`
and wait answer.

**UPDATE**: In last case when connection is recovered it's seems ok and listener continues to work correct. But sometimes it's wrong and listener doesn't continue to listen.

**Comment by anotheri** [comment]
@podviaznikov @chirag04

I run very simple listener last evening:

```
var MailListener = require("mail-listener");

var mailListener = new MailListener({
  username: myUsername + "@gmail.com",
  password: myPassword,
  host: "imap.gmail.com",
  port: 993,
  secure: true,
  mailbox: "INBOX",
  markSeen: true,
  fetchUnreadOnStart: true
});

mailListener.on("server:connected", function(){
  console.log("imapConnected");
});

mailListener.on("server:disconnected", function(){
  console.log("imapDisconnected");
});

mailListener.on("server:error", function(error){
  console.log("imapError", error);
});

mailListener.on("mail:parsed", function(mail){
  console.log("emailParsed", mail.attachments);
});

mailListener.start();
```

But this morning (after ~12 hours) I found it's down without any errors in the console. In the console was just this output:

```
23 May 17:30:43 - connect to mail server: success
imapConnected
23 May 17:30:43 - open mail box 'INBOX': success
23 May 17:30:43 - found 0 emails
23 May 17:30:43 - no email were found
```

Could anyone help me? What's wrong with it?
Is connection timeout or something else?
What's logic must be if I want listener to work all the time (24/7)?
Should I stop and start it again by timeout?

**Comment by anotheri** [comment]
It's down every 1 hour after last server activity. Seems like mail server (gmail) timeout.

**Comment by anotheri** [comment]
For now I found only one way to make it works by day and night.

First, I made a listener (file **lstnr.js**):

```
var MailListener = require("mail-listener");

var mailListener = new MailListener({
    username: myUsername,
    password: myPassword,
    host: "imap.gmail.com",
    port: 993,
    secure: true,
    mailbox: "INBOX",
    markSeen: true,
    fetchUnreadOnStart: true
});

mailListener.on("server:connected", function(){
    console.log("imapConnected");
});

mailListener.on("server:disconnected", function(){
    console.log("imapDisconnected");
});

mailListener.on("error", function(error){
    console.log("imapError", error);
});

mailListener.on("mail:parsed", function(mail){
    console.log("emailParsed", mail.attachments);
});

mailListener.start();
```

Second, I made a http express server that provide a startup handler for my listener by [forever-monitor module](https://github.com/nodejitsu/forever-monitor) (file **main.js**):

```
var express = require('express');
var app     = express();
var forever = require('forever-monitor');

var child = new (forever.Monitor)('./lstnr.js', {
    // silent: true
});

child.on('exit', function (forever) {
    console.log('========================== lstnr.js is EXITED ==========================');
    console.log(forever);
    console.log('========================== lstnr.js is EXITED END ==========================');
});
child.on('restart', function (forever) {
    console.log('========================== lstnr.js is RESTARTED ==========================');
    console.log(forever);
    console.log('========================== lstnr.js is RESTARTED END ==========================');
});
child.on('start', function (process, data) {
    console.log('========================== lstnr.js is STARTED ==========================');
    console.log(process, data);
    console.log('========================== lstnr.js is STARTED END ==========================');
});
child.on('stop', function (process) {
    console.log('========================== lstnr.js is STOPPED ==========================');
    console.log(process);
    console.log('========================== lstnr.js is STOPPED END ==========================');
});
child.on('error', function (err) {
    console.log('========================== lstnr.js has ERROR ==========================');
    console.log(err);
    console.log('========================== lstnr.js has ERROR END ==========================');
});

app.use(app.router);
app.use(function(err, req, res, next) {
    if(!err){
        next();
    } else {
        console.log(err);
        console.error(err.stack);
        res.send(500, 'Error! Something broke!');
    }
});

app.get('/restart', function(req, res){
    child.restart();
    res.send('Listener is RESTARTED.');
});

app.get('/stop', function(req, res){
    child.stop();
    res.send('Listener is STOPPED.');
});

app.listen(3000, function() {
    console.log("Listening on 3000");
    child.start();
});
```

And run `node mail.js` to start it. Listener's started up as child process. And it will be restarted every time when it's down.
`http://localhost:3000/restart` — link for a force restarting mail listener process.
`http://localhost:3000/stop` — link for a force stop mail listener process.

**Comment by mostafiz57** [comment]
Thanks @anotheri , It is working for me .
