### ISSUE TITLE
Install is sucessful but example "Cannot find module 'mail-listener'".

### ISSUE THREAD

**Issue by reggi** [circuithub/mail-listener#3]
I'm on a mac.

I installed `mail-listener` with `npm`

```
thomas@workstation:~/Desktop/gamma/projects/incubaker/open-product2$ npm install mail-listener
npm info it worked if it ends with ok
npm info using npm@1.1.61
npm info using node@v0.8.6
npm WARN invalid config registry=""
npm WARN invalid config Must be a full url with 'http://'
npm info trying registry request attempt 1 at 13:32:12
npm http GET https://registry.npmjs.org/mail-listener
npm http 304 https://registry.npmjs.org/mail-listener
npm info install mail-listener@0.2.0 into /Users/thomas/Desktop/gamma/projects/incubaker/open-product2
npm info installOne mail-listener@0.2.0
npm WARN engine mail-listener@0.2.0: wanted: {"node":"~0.6.9"} (current: {"node":"v0.8.6","npm":"1.1.61"})
npm info /Users/thomas/Desktop/gamma/projects/incubaker/open-product2/node_modules/mail-listener unbuild
npm info preinstall mail-listener@0.2.0
npm info trying registry request attempt 1 at 13:32:13
npm http GET https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/coffee-script
npm info install coffee-script@1.4.0 into /Users/thomas/Desktop/gamma/projects/incubaker/open-product2/node_modules/mail-listener
npm info installOne coffee-script@1.4.0
npm info /Users/thomas/Desktop/gamma/projects/incubaker/open-product2/node_modules/mail-listener/node_modules/coffee-script unbuild
npm info preinstall coffee-script@1.4.0
npm info build /Users/thomas/Desktop/gamma/projects/incubaker/open-product2/node_modules/mail-listener/node_modules/coffee-script
npm info linkStuff coffee-script@1.4.0
npm info install coffee-script@1.4.0
npm info postinstall coffee-script@1.4.0
npm info build /Users/thomas/Desktop/gamma/projects/incubaker/open-product2/node_modules/mail-listener
npm info linkStuff mail-listener@0.2.0
npm info install mail-listener@0.2.0
npm info postinstall mail-listener@0.2.0
mail-listener@0.2.0 node_modules/mail-listener
└── coffee-script@1.4.0
npm info ok 
```

I run the example

```
thomas@workstation:~/Desktop/gamma/projects/incubaker/open-product2$ node listener.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'mail-listener'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/thomas/Desktop/gamma/projects/incubaker/open-product2/listener.js:4:16)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
```

Change directory into `node_modules/`

```
thomas@workstation:~/Desktop/gamma/projects/incubaker/open-product2$ cd ./node_modules/
```

Shows that `mail-listener` is there.

```
thomas@workstation:~/Desktop/gamma/projects/incubaker/open-product2/node_modules$ ls -la
total 0
drwxr-xr-x  13 thomas  staff  442 Nov 20 13:32 .
drwxr-xr-x@ 12 thomas  staff  408 Nov 20 13:26 ..
drwxr-xr-x   4 thomas  staff  136 Nov 15 12:27 .bin
drwxr-xr-x  15 thomas  staff  510 Nov 15 12:27 express
drwxr-xr-x   7 thomas  staff  238 Nov 15 15:34 imap
drwxr-xr-x  15 thomas  staff  510 Nov 15 12:27 jade
drwxr-xr-x  12 thomas  staff  408 Nov 15 16:32 jquery
drwxr-xr-x   7 thomas  staff  238 Nov 15 12:27 jsdom
drwxr-xr-x   8 thomas  staff  272 Nov 20 13:32 mail-listener
drwxr-xr-x  10 thomas  staff  340 Nov 15 15:34 mailparser
drwxr-xr-x  13 thomas  staff  442 Nov 15 12:43 mongolian
drwxr-xr-x  14 thomas  staff  476 Nov 15 12:28 request
drwxr-xr-x  12 thomas  staff  408 Nov 15 16:15 string
thomas@workstation:~/Desktop/gamma/projects/incubaker/open-product2/node_modules$ 
```

**Comment by reggi** [comment]
I installed it again on a fresh express install and it spewed out a lot more in the installation process. But still the same error occurs.

**Comment by reggi** [comment]
Is this a coffee script thing?

**Comment by simontabor** [comment]
Broken for me too

**Comment by podviaznikov** [comment]
Right now this can be used only in CoffeeScript projects. Need to add JS version.

**Comment by simontabor** [comment]
Wrote a JS version - https://github.com/simontabor/node-imap-listener. Need to add a credit to this project as it's pretty much a translation

**Comment by podviaznikov** [comment]
add JS support. See readme for JS example.
