### ISSUE TITLE
 undefined is not a function

### ISSUE THREAD

**Issue by drkonafa** [circuithub/mail-listener#30]
blank app and used the code example. always getting 
 undefined is not a function

/Applications/MAMP/htdocs/mail/node_modules/mail-listener/dist/mail.listener.js:24
      this.imap = new ImapConnection({
                  ^
TypeError: undefined is not a function
    at new MailListener (/Applications/MAMP/htdocs/mail/node_modules/mail-listener/dist/mail.listener.js:24:19)
    at Object.<anonymous> (/Applications/MAMP/htdocs/mail/app.js:3:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by WA9ACE** [comment]
Same happening here. I thought it was just me.

**Comment by drkonafa** [comment]
Aha! please post solution here if you solve it.

**Comment by drkonafa** [comment]
It's about node imap library. 
the newest library has var Imap = require('imap') instead of require("imap").ImapConnection;

That overcame that specific error but still doesn't work..with no error messages in console.

**Comment by chirag04** [comment]
Yeah node-imap changed.

I rewrote this lib. Check https://github.com/chirag04/mail-listener2
