### ISSUE TITLE
Cannot call method 'on' of undefined

### ISSUE THREAD

**Issue by eps90** [circuithub/mail-listener#4]
Hi. I've installed mail-listener via npm. When I tried to run example script from README in plain JavaScript it worked fine. But when I send test email into my email box, application crashed and I got error:

```
28 Jan 19:48:13 - successfully connected to mail server
imap Connected
28 Jan 19:48:14 - successfully opened mail box
28 Jan 19:48:44 - new mail arrived with id 1
28 Jan 19:48:44 - found 1 emails

/home/kuba/testy/mailparser/node_modules/mail-listener/dist/mail.listener.js:65
                    return fetch.on("message", function(msg) {
                                 ^
TypeError: Cannot call method 'on' of undefined
    at ImapConnection.MailListener.start (/home/kuba/testy/mailparser/node_modules/mail-listener/dist/mail.listener.js:65:34)
    at ondata (/home/kuba/testy/mailparser/node_modules/mail-listener/node_modules/imap/lib/imap.js:675:30)
    at CleartextStream.ondata (/home/kuba/testy/mailparser/node_modules/mail-listener/node_modules/imap/lib/imap.js:602:16)
    at CleartextStream.EventEmitter.emit (events.js:96:17)
    at CleartextStream.CryptoStream._push (tls.js:540:12)
    at SecurePair.cycle (tls.js:898:20)
    at EncryptedStream.CryptoStream.write (tls.js:285:13)
    at Socket.ondata (stream.js:38:26)
    at Socket.EventEmitter.emit (events.js:96:17)
    at TCP.onread (net.js:397:14)
```

**Comment by podviaznikov** [comment]
fixed
